### ISSUE TITLE
Compilation Failed when starting debug session

### ISSUE THREAD

**Issue by Puritanic** [rokucommunity/vscode-brightscript-language#268]
My guess is that this is caused by this line in one of my HTTP handlers:

```brs
mutationData.query = readAsciiFile("pkg:/mutations/addDevice.gql")
```

Is there any limitation for reading project files with readAsciiFile? I've searched through Issues and couldn't find anything.

I'm also receiving these errors in VSCode dev tools:

```txt
  ERR ENOENT: no such file or directory, open 'extension-output-#4': Error: ENOENT: no such file or directory, open 'extension-output-#4'
log.ts:197   ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3184:226)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3183:532
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:536)
log.ts:197   ERR Cannot determine fsPath for uri: file:///Users/dtasevski/Projects/roku/src/components/services/Auth.brs: Error: Cannot determine fsPath for uri: file:///Users/dtasevski/Projects/roku/src/components/services/Auth.brs
    at BrighterScriptPreviewCommand.getSourcePathFromPreviewUri (/Users/dtasevski/.vscode-insiders/extensions/celsoaf.brightscript-2.5.4/dist/commands/BrighterScriptPreviewCommand.js:224:23)
    at /Users/dtasevski/.vscode-insiders/extensions/celsoaf.brightscript-2.5.4/dist/commands/BrighterScriptPreviewCommand.js:57:31
    at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at t.ExtHostEditors.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:833)
    at m._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:816:707)
    at m._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:816:399)
    at m._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:59)
    at m._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:813:886)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:812:34
    at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:381)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1004:179
    at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:381)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:921)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:926
    at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at p.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:851)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:203
    at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:500)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

I have extension version 2.5.4 installed

VSCode:
```
Version: 1.48.0-insider
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:40:23.559Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
```

**Comment by Puritanic** [comment]
Figured that I haven't passed this file's path to bsconfig files property... Closing
