### ISSUE TITLE
Publish errors "500" or "write EPIPE" with Big Sur

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#311]
Me and some of my colleagues have recently upgraded to macOS Big Sur (11.3.1), and we've started having errors during the publish process while launching a debug session. The error is somewhat inconsistent and doesn't happen everytime, but can either be an error 500 coming from the box itself, or a write EPIPE (albeit less common).

All the extension outputs is this:

```
DebugServer: Moving selected files to staging area
DebugServer: Adding stop statements for active breakpoints
DebugServer: Creating zip archive from project sources
DebugServer: Connecting to Roku via telnet at 192.168.111.109
DebugServer: Exiting any active brightscript debugger
DebugServer: Encountered an issue during the publish process
DebugServer: Invalid response code: 500
```

After modifying the extension's `roku-deploy` and `roku-debug` to output some extra info to a file, this is what I get:

```
[1620824193952] roku-deploy request 1
    {"url":"http://192.168.111.109:8060/keypress/Home"}
[1620824194001] roku-deploy response 1 SUCCESS
    {"statusCode":200,"body":"","headers":{"server":"Roku/10.0.0 UPnP/1.0 Roku/10.0.0","content-length":"0"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.111.109:8060","port":"8060","hostname":"192.168.111.109","hash":null,"search":null,"query":null,"pathname":"/keypress/Home","path":"/keypress/Home","href":"http://192.168.111.109:8060/keypress/Home"},"method":"POST","headers":{"content-length":0}}}
[1620824194445] roku-deploy request 2
    {"url":"http://192.168.111.109:80/plugin_install","auth":{"user":"rokudev","pass":"rokudev","sendImmediately":false},"formData":{"mysubmit":"Replace","archive":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":2,"path":"/Users/luis.soares/dev/scenegraph-master-sample/DetailsScreen/out/roku-deploy.zip","fd":25,"flags":"r","mode":438,"end":null,"autoClose":true,"bytesRead":0,"closed":false}}}
[1620824194472] roku-deploy response 2 SUCCESS
    {"statusCode":500,"body":"Error 500: Server Error\nClient closed connection","headers":{"content-length":"48","content-type":"text/plain","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.111.109:80","port":"80","hostname":"192.168.111.109","hash":null,"search":null,"query":null,"pathname":"/plugin_install","path":"/plugin_install","href":"http://192.168.111.109:80/plugin_install"},"method":"POST","headers":{"content-type":"multipart/form-data; boundary=--------------------------691106484946904150540282","content-length":224233,"authorization":"Digest username=\"rokudev\", realm=\"rokudev\", nonce=\"1620824194\", uri=\"/plugin_install\", qop=auth, response=\"45113f32e3cd23a69693ca9624ca305c\", nc=00000001, cnonce=\"73cd33b56dce4ff793ef15d4f4ce170b\"","referer":"http://192.168.111.109:80/plugin_install"}}}
[1620824194473] roku-debug publish error
    Error: Invalid response code: 500
    at new InvalidDeviceResponseCodeError (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/Errors.js:19:28)
    at RokuDeploy.checkRequest (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/RokuDeploy.js:873:19)
    at RokuDeploy.<anonymous> (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/RokuDeploy.js:832:34)
    at step (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/RokuDeploy.js:50:23)
    at Object.next (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/RokuDeploy.js:31:53)
    at fulfilled (/Users/luis.soares/.vscode/extensions/rokucommunity.brightscript-2.20.1/node_modules/roku-deploy/dist/RokuDeploy.js:22:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    {"response":{"statusCode":500,"body":"Error 500: Server Error\nClient closed connection","headers":{"content-length":"48","content-type":"text/plain","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.111.109:80","port":"80","hostname":"192.168.111.109","hash":null,"search":null,"query":null,"pathname":"/plugin_install","path":"/plugin_install","href":"http://192.168.111.109:80/plugin_install"},"method":"POST","headers":{"content-type":"multipart/form-data; boundary=--------------------------691106484946904150540282","content-length":224233,"authorization":"Digest username=\"rokudev\", realm=\"rokudev\", nonce=\"1620824194\", uri=\"/plugin_install\", qop=auth, response=\"45113f32e3cd23a69693ca9624ca305c\", nc=00000001, cnonce=\"73cd33b56dce4ff793ef15d4f4ce170b\"","referer":"http://192.168.111.109:80/plugin_install"}}},"body":"Error 500: Server Error\nClient closed connection"}
[1620824194473] roku-debug node detail
    /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer), v14.16.0
[1620824194489] roku-deploy request 3
    {"url":"http://192.168.111.109:8060/keypress/Home"}
[1620824194531] roku-deploy response 3 SUCCESS
    {"statusCode":200,"body":"","headers":{"server":"Roku/10.0.0 UPnP/1.0 Roku/10.0.0","content-length":"0"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.111.109:8060","port":"8060","hostname":"192.168.111.109","hash":null,"search":null,"query":null,"pathname":"/keypress/Home","path":"/keypress/Home","href":"http://192.168.111.109:8060/keypress/Home"},"method":"POST","headers":{"content-length":0}}}
```

The issue only happens when deploying inside VSC. Deploying the same zip file using `roku-deploy` outside VSC's sandbox (which uses my local node), or even using the upload form accessible through the box's IP, always works.

Managed to reproduce the error at least once in every combo I've tried, which included:

- installing different versions of the extension (from 2.17.0 up to 2.20.1)
- installing different versions of VS Code (from 1.54 up to 1.56, and even tried 1.45)
- toggling debug server on and off, and experimenting with multiple launch settings
- running multiple projects, including [this roku sample](https://github.com/rokudev/scenegraph-master-sample/tree/master/DetailsScreen)
- installing in different boxes (Roku Ultra 4670X on FW 10.0, and Roku Express 3900X on FW 9.4)
- connecting to different wifi networks (VPN vs home wifi)

**Comment by chrisdp** [comment]
@luis-soares-sky Thanks for all the details! We will keep you updated as we try to find the root cause of the issue.

**Comment by luis-soares-sky** [comment]
Some extra information from a colleague of mine with the same issue:

> I just had the 500 error 3 times in a row. I ran this: `rm -rf build && rm -rf out` and then tried again, and the build completed and deployed.
I've only done this once so it could be a coincidence, but I was purposefully keeping changes to a minimum for testing purposes and that command was literally the only thing I did: no code changes, no app restarts
>
> Just got the 500 error again, and this time the above command is NOT solving the issue
>
> After repeated failures, even after a VSC update and reboot, I built manually and afterwards VSC builds worked again. As above, could just be coincidence but there had been at least 5 failures before the manual build
>
> Again no code changes between the two
>
> I think they are just coincidences. Seems to be a bug in Big Sur relating to memory addresses

**Comment by chrisdp** [comment]
@luis-soares-sky question for your team. Does your teammates tend to use the reload option or do they stop -> start between debug sessions?

**Comment by luis-soares-sky** [comment]
> Does your teammates tend to use the reload option or do they stop -> start between debug sessions?

It's a mixed bag, some (includingme) use the reload option more often, while others use stop -> start because reload was giving them issues (even before Big Sur, reload sometimes wouldn't deploy the app).

**Comment by luis-soares-sky** [comment]
Found the culprit: Falcon CrowdStrike 6.17 had a network layer that corrupted POST requests with payloads.

> For a bit more specific background on this, I think we deduced that Crowdstrike stripped off a good chunk of data from the beginning of the message / payload from large POST requests (eg, HTTP host/ path / verb), and some data being read off in the middle of the message.
>
> This is reproducible when disabling (Make Service Inactive) and enabling (Make Service Active) the Falcon 1 network service via System Preferences > Network. And then Apply the changes for it to take effect.
>
> All this thereby resulting in large POST requests being malformed once it reaches our BE services, and as a consequence failing image / video / zip upload HTTP data requests.

Closing.
