### ISSUE TITLE
Unclosed #if causes lots of errors to be spit out

### ISSUE THREAD

**Issue by triwav** [rokucommunity/vscode-brightscript-language#328]
If you start typing a conditional compilation if as soon as you you finish the `#if` it start throwing errors and switch the output window you're on

```
[Error - 4:21:46 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: TypeError: Cannot read property 'end' of undefined
    at Util.rangesIntersect (/Users/bleighty/.vscode/extensions/rokucommunity.brightscript-2.23.0/node_modules/brighterscript/dist/util.js:438:15)
    at /Users/bleighty/.vscode/extensions/rokucommunity.brightscript-2.23.0/node_modules/brighterscript/dist/Program.js:669:42
    at Array.filter (<anonymous>)
    at Program.getCodeActions (/Users/bleighty/.vscode/extensions/rokucommunity.brightscript-2.23.0/node_modules/brighterscript/dist/Program.js:669:18)
    at /Users/bleighty/.vscode/extensions/rokucommunity.brightscript-2.23.0/node_modules/brighterscript/dist/LanguageServer.js:459:61
    at Array.flatMap (<anonymous>)
    at LanguageServer.onCodeAction (/Users/bleighty/.vscode/extensions/rokucommunity.brightscript-2.23.0/node_modules/brighterscript/dist/LanguageServer.js:459:14)
  Code: -32603 
```

**Comment by TwitchBronBron** [comment]
I believe this is fixed in the latest brighterscript v1 alphas since we added parser support for conditional compile.
