### ISSUE TITLE
debugger occasionally cannot resolve threads - will just hang on a runtime error

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#36]
this code from brightscriptDebugSession will sometimes crash on ` threads[0].threadId` - `threadId` is not defined.. :
```
  private async connectRokuAdapter(host: string) {
    //register events
    let firstSuspend = true;
    this.rokuAdapter = new RokuAdapter(host);

    //when the debugger suspends (pauses for debugger input)
    this.rokuAdapter.on('suspend', async () => {
      let threads = await this.rokuAdapter.getThreads();
      let threadId = threads[0].threadId;```

**Comment by georgejecook** [comment]
here's the error

```(node:76895) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'threadId' of undefined
warning.js:18
    at BrightScriptDebugSession.<anonymous> (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/src/brightScriptDebugSession.ts:548:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/georgecook/Documents/h7ci/hope/vscode/vscode-brightscript-language/out/brightScriptDebugSession.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:76895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:76895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:18
i```

**Comment by TwitchBronBron** [comment]
This is a hard one to debug. Could you provide a sample repository that reproduces the issue? My guess is that this is some type of timing issue, but as such, it's still really hard to track down without a working example (even if the example only fails 1/4 of the time, that's better than nothing).

**Comment by TwitchBronBron** [comment]
@georgejecook is this still an issue for you? If so, do you have any more information that could help track this down?

**Comment by chrisdp** [comment]
@georgejecook i thunk we can call this one fixed now what do you think?

**Comment by georgejecook** [comment]
yep.
