### ISSUE TITLE
Extension keeps running after closing vscode with 100% cpu use

### ISSUE THREAD

**Issue by DusanLesan** [rokucommunity/vscode-brightscript-language#486]
Starting with the version `2.40.1`, plugin is no longer closed after exiting vscode on linux. Furthermore, the extension starts utilizing 100% of one cpu thread.
![active-20230524-160207](https://github.com/rokucommunity/vscode-brightscript-language/assets/20520590/92be08bb-81bb-4688-b279-661d6601c0f9)
In this image, you can see plugin getting left behind seconds after closing vscode. Sometimes, I have even seen several different plugin tasks running after closing vscode

v`2.40.0` and before it worked fine

STR:

- Start vscode
- Start debugging
- Exit vscode

vscode info:
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-12T07:29:20.595Z
Electron: 22.3.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.3-arch1-1
Sandboxed: No

**Comment by TwitchBronBron** [comment]
I believe we fixed this issue (or most of.it), in 2.40.4. can you install that version, and then reboot your computer, and report back if you're still seeing it in 2.40.4.

**Comment by DusanLesan** [comment]
Some logs I got at the moment of closing vscode (around 2023-05-24 21:45:28.917):

<details>
<summary>File exthost.log</summary>

```
2023-05-24 21:44:19.835 [info] ExtensionService#_doActivateExtension vscode.debug-server-ready, startup: false, activationEvent: 'onDebugResolve'
2023-05-24 21:45:28.917 [info] Extension host terminating: renderer closed the MessagePort
2023-05-24 21:45:28.952 [warning] Canceled
2023-05-24 21:45:28.960 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at D (/usr/lib/code/extensions/git/dist/main.js:2:1259661)
	at v.invoke (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at i.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (/usr/lib/code/extensions/git/dist/main.js:2:1274494)
	at /usr/lib/code/extensions/git/dist/main.js:2:1278940
	at Array.forEach (<anonymous>)
	at g.dispose (/usr/lib/code/extensions/git/dist/main.js:2:1278926)
	at t.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:96:12369)
	at t.dispose (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:96:12504)
	at t.<anonymous> (/usr/lib/code/extensions/git/dist/main.js:2:1261791)
	at t.dispose (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:96:12504)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.963 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at ActionRunners.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:35695)
	at /home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613387
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613372)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.965 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at ActionRunners.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:35695)
	at /home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613387
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613372)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.966 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at ActionRunners.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:35695)
	at /home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613387
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:613372)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.969 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36350)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.973 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36350)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.976 [error] Canceled: Canceled
	at new l (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:104563)
	at a.O (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:11657)
	at H.<computed>.V.charCodeAt.H.<computed> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:110:8947)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124729)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at C.registerCommand.description (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:123398)
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:125315)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124205)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:98:124105)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:24043)
	at g (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:878971)
	at c (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:883651)
	at ActionRunners._updateContextKeys (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:37690)
	at s (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36109)
	at RegisteredActionRunner.unregister (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36253)
	at RegisteredActionRunner.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:34918)
	at Object.dispose (/home/dusan/.config/code-oss/extensions/eamodio.gitlens-13.6.0-universal/dist/gitlens.js:1:36350)
	at T (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:10:12080)
	at v.Y (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:11173)
	at /usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9157
	at Array.map (<anonymous>)
	at v.R (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9144)
	at v.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:112:9415)
	at d.terminate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:116:1544)
	at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:34439)
	at MessagePortMain.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:126:30578)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-05-24 21:45:28.977 [info] Extension host with pid 4340 exiting with code 0
```

</details>

**Comment by DusanLesan** [comment]
I have tried now the latest version and the issue is still actual. I have stopped the auto updates since it was bad enough for me. I could still debug but I would rather use 2.39.0 than deal with the rogue processes every day

**Comment by DusanLesan** [comment]
@TwitchBronBron Any progress on this? I have experienced this issue on my new computer too but since it uses the same setup as previous (arch + X + dwm + code OSS + plugin from open-vsx.org), I have also tried it in a virtual machine using ubuntu 22.04 with vscode from store and debugging an app from rokudev/samples
<details><summary>Image</summary>
<p>

![image](https://github.com/rokucommunity/vscode-brightscript-language/assets/20520590/d8eefe41-e18a-4099-96b0-19793c637728)

</p>
</details>

**Comment by TwitchBronBron** [comment]
Sadly I haven't had the time to investigate lately. Does this reproduce every single time for you?

To help troubleshoot this issue, we added some better logging a while back. Could you do the following:
1. kill all rogue processes
2. enable `fileLogging` in your launch.json (you can accept the defaults, either set it to `true` or the whole json chunk)
4. Now do whatever debugging steps required to trigger the rogue process
5. include the logs here. (you might need to sanitize them a little)

**Comment by DusanLesan** [comment]
[2023-09-13T14∶49∶29-debugger.log](https://github.com/rokucommunity/vscode-brightscript-language/files/12597580/2023-09-13T14.49.29-debugger.log)
[2023-09-13T14∶49∶29-rokuDevice.log](https://github.com/rokucommunity/vscode-brightscript-language/files/12597582/2023-09-13T14.49.29-rokuDevice.log)

Yes, it happens for me every time I close vscode while debugger is running
Here are the logs. It made all these `Tried to call `.shutdown()` entries in less than 20 seconds before I killed the process

**Comment by TwitchBronBron** [comment]
@DusanLesan [release v2.44.0](https://github.com/rokucommunity/vscode-brightscript-language/releases/tag/v2.44.0) introduced several fixes that attempt to address this issue. Can you try that out and report back?

**Comment by DusanLesan** [comment]
<details><summary>It is still actual on that version</summary>
<p>

[2023-10-27T20∶31∶26-debugger.log (thousands of lines removed since it was over 100M when I killed all rokucommunity processes from the image below)](https://github.com/rokucommunity/vscode-brightscript-language/files/13192113/2023-10-27T20.31.26-debugger.log)

![active-20231027-202640](https://github.com/rokucommunity/vscode-brightscript-language/assets/20520590/5b88b047-e129-40c5-a2b4-ae88262b5f50)

</p>
</details>

**Comment by JoeD4321** [comment]
I am seeing this issue as well.  Hopefully this information will be helpful.

My Environment:
OS: Fedora Linux 41 - Kernel 6.12.6-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz --- 6 CPU Cores - 2 Threads/Core

VS Code Info:
Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.12.6-200.fc41.x86_64
BrightScript Language Plugin: 2.51.0

How I reproduce issue:
I used the simplest public Roku project I could find: hello-world-master from Roku samples: [(https://github.com/rokudev/samples/tree/master/getting%20started/hello-world-master)]

1. Clone the project and configure to run on your system
2. Click "Run"/"Run Without Debugging" in VS Code
3. Verify "Hello, World" is displayed on your roku device
4. Leave the app running
5. Close Code with the "X" in the upper right of screen

When I closed Code, all the Code processes disappeared except for one:
```
UID          PID    PPID  C STIME TTY          TIME CMD
jtest     885577    3257 51 15:00 ?        00:01:07 /usr/share/code/code -e delete process.env.ELECTRON_RUN_AS_NODE;require(process.argv[1]) /home/jtest/.vscode/extensions/rokucommunity.brightscript-2.51.0/dist/debugAdapter.js

```
This process has 12 threads, although it seems only one is active
This process is in a tight loop writing to ```2025-01-09T15∶00∶56-debugger.log``` in the project ```logs``` directory.  Contents being millions of ```[15:06:56.460][LOG  ] [dap][session] [shutdown] Tried to call `.shutdown()` again. Returning the same promise``` errors.

The Linux ```strace``` command shows that it was in a loop doing these instructions:
```
write(1, "Content-Length: 195\r\n\r\n{\"type\":\"event\",\"body\":{\"line\":\"[15:52:16.724][LOG  ] [dap][session] [shutdown] Tried to call `.shutdown()` again. Returning the same promise\"},\"event\":\"DebugServerLogOutputEvent\",\"seq\":30810431}", 218) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=885577, si_uid=1000} ---
mkdir("/home/jtest/vssandbox/hello-world-master/logs", 0777) = -1 EEXIST (File exists)
statx(AT_FDCWD, "/home/jtest/vssandbox/hello-world-master/logs", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_blksize=4096, stx_attributes=0, stx_nlink=2, stx_uid=1000, stx_gid=1000, stx_mode=S_IFDIR|0755, stx_ino=671346, stx_size=4096, stx_blocks=8, stx_attributes_mask=STATX_ATTR_COMPRESSED|STATX_ATTR_IMMUTABLE|STATX_ATTR_APPEND|STATX_ATTR_NODUMP|STATX_ATTR_ENCRYPTED|STATX_ATTR_AUTOMOUNT|STATX_ATTR_MOUNT_ROOT|STATX_ATTR_VERITY|STATX_ATTR_DAX, stx_atime={tv_sec=1736453150, tv_nsec=570971503} /* 2025-01-09T15:05:50.570971503-0500 */, stx_btime={tv_sec=1736370538, tv_nsec=691636932} /* 2025-01-08T16:08:58.691636932-0500 */, stx_ctime={tv_sec=1736452858, tv_nsec=303633928} /* 2025-01-09T15:00:58.303633928-0500 */, stx_mtime={tv_sec=1736452858, tv_nsec=303633928} /* 2025-01-09T15:00:58.303633928-0500 */, stx_rdev_major=0, stx_rdev_minor=0, stx_dev_major=253, stx_dev_minor=2, stx_mnt_id=0x3d}) = 0
openat(AT_FDCWD, "/home/jtest/vssandbox/hello-world-master/logs/2025-01-09T15\342\210\26600\342\210\26656-debugger.log", O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC, 0666) = 3
write(3, "[15:52:16.724][LOG  ] [dap][session] [shutdown] Tried to call `.shutdown()` again. Returning the same promise\n", 110) = 110
close(3)                                = 0

```

### Workaround

In testing, I found that if you leave the app running and exit Code, the problem happens whether using the debugger or not.  However,  I have found that if you stop your Roku app execution manually first, before exiting Code, you avoid this problem completely.

Let me know if I can provide more infio.

**Comment by chrisdp** [comment]
I was able to replicate a version of this issue with tests in https://github.com/rokucommunity/roku-debug/pull/383
