### ISSUE TITLE
DebugServer: Encountered an issue during the publish process same error on all my projects when debugging

### ISSUE THREAD

**Issue by faverpaz** [rokucommunity/vscode-brightscript-language#606]
DebugServer: Encountered an issue during the publish process
DebugServer: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: E

at error (.....\.vscode\extensions\rokucommunity.brightscript-2.50.5\node_modules\sax\lib\sax.js:651:10)
    at strictFail (.......\.vscode\extensions\rokucommunity.brightscript-2.50.5\node_modules\sax\lib\sax.js:677:7)
    at beginWhiteSpace (......\.vscode\extensions\rokucommunity.brightscript-2.50.5\node_modules\sax\lib\sax.js:951:7)
    at SAXParser.write (.....\.vscode\extensions\rokucommunity.brightscript-2.50.5\node_modules\sax\lib\sax.js:1006:11)

**Comment by TwitchBronBron** [comment]
That's very interesting, I've never seen this issue before. 

Can you try cloning these sample projects, does it happen in them as well?

https://github.com/rokucommunity/sample-projects

**Comment by faverpaz** [comment]
Hello, same problem, everything worked fine just from one moment to the next it could no longer be run directly on Roku but if it creates the zip and I can upload it manually on Roku but all my projects and the new ones downloaded have the same problem I already tried changing versions of Node without results

**Comment by JamesMLV** [comment]
I was also running into this, debugged into it for a while, figured out the string it was choking on was "ECP command not allowed in Limited mode".

There's a setting on the roku: Settings > System > Advanced system Settings > Control by mobile apps
Setting that to Permissive seemed to fix things.

**Comment by natonic77** [comment]
@JamesMLV Thanks for this. Permissive solved the problem for me.

**Comment by TwitchBronBron** [comment]
I'm actively working on some fixes in our tooling to better detect this, and hopefully recover enough to still be able to run a debug session. I'll update this ticket once I've landed the fix.

**Comment by TwitchBronBron** [comment]
I believe we have fixed the crash related to this.
